/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { FunctionFragment, Result } from "@ethersproject/abi";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  CallOverrides,
  ethers,
  PopulatedTransaction,
  Signer,
} from "ethers";
import { TypedEvent, TypedEventFilter, TypedListener } from "./commons";

interface Keep3rHelperInterface extends ethers.utils.Interface {
  functions: {
    "BOOST_BASE()": FunctionFragment;
    "KP3R()": FunctionFragment;
    "KP3R_WETH_POOL()": FunctionFragment;
    "MAX()": FunctionFragment;
    "MIN()": FunctionFragment;
    "TARGETBOND()": FunctionFragment;
    "bonds(address)": FunctionFragment;
    "getKP3RsAtTick(uint256,int56,uint256)": FunctionFragment;
    "getPoolTokens(address)": FunctionFragment;
    "getQuoteAtTick(uint128,int56,uint256)": FunctionFragment;
    "getRewardAmount(uint256)": FunctionFragment;
    "getRewardAmountFor(address,uint256)": FunctionFragment;
    "getRewardBoostFor(uint256)": FunctionFragment;
    "isKP3RToken0(address)": FunctionFragment;
    "keep3rV2()": FunctionFragment;
    "observe(address,uint32[])": FunctionFragment;
    "quote(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BOOST_BASE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "KP3R", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "KP3R_WETH_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TARGETBOND",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bonds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getKP3RsAtTick",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteAtTick",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardAmountFor",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRewardBoostFor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isKP3RToken0",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "keep3rV2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "observe",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "quote", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "BOOST_BASE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "KP3R", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "KP3R_WETH_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TARGETBOND", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bonds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getKP3RsAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardAmountFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRewardBoostFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKP3RToken0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keep3rV2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "observe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;

  events: {};
}

export class Keep3rHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: Keep3rHelperInterface;

  functions: {
    BOOST_BASE(overrides?: CallOverrides): Promise<[BigNumber]>;

    KP3R(overrides?: CallOverrides): Promise<[string]>;

    KP3R_WETH_POOL(overrides?: CallOverrides): Promise<[string]>;

    MAX(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN(overrides?: CallOverrides): Promise<[BigNumber]>;

    TARGETBOND(overrides?: CallOverrides): Promise<[BigNumber]>;

    bonds(
      _keeper: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _amountBonded: BigNumber }>;

    getKP3RsAtTick(
      _liquidityAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _kp3rAmount: BigNumber }>;

    getPoolTokens(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { _token0: string; _token1: string }>;

    getQuoteAtTick(
      _baseAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _quoteAmount: BigNumber }>;

    getRewardAmount(
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _amount: BigNumber }>;

    getRewardAmountFor(
      _keeper: string,
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _kp3r: BigNumber }>;

    getRewardBoostFor(
      _bonds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _rewardBoost: BigNumber }>;

    isKP3RToken0(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { _isKP3RToken0: boolean }>;

    keep3rV2(overrides?: CallOverrides): Promise<[string]>;

    observe(
      _pool: string,
      _secondsAgo: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        _tickCumulative1: BigNumber;
        _tickCumulative2: BigNumber;
        _success: boolean;
      }
    >;

    quote(
      _eth: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _amountOut: BigNumber }>;
  };

  BOOST_BASE(overrides?: CallOverrides): Promise<BigNumber>;

  KP3R(overrides?: CallOverrides): Promise<string>;

  KP3R_WETH_POOL(overrides?: CallOverrides): Promise<string>;

  MAX(overrides?: CallOverrides): Promise<BigNumber>;

  MIN(overrides?: CallOverrides): Promise<BigNumber>;

  TARGETBOND(overrides?: CallOverrides): Promise<BigNumber>;

  bonds(_keeper: string, overrides?: CallOverrides): Promise<BigNumber>;

  getKP3RsAtTick(
    _liquidityAmount: BigNumberish,
    _tickDifference: BigNumberish,
    _timeInterval: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPoolTokens(
    _pool: string,
    overrides?: CallOverrides
  ): Promise<[string, string] & { _token0: string; _token1: string }>;

  getQuoteAtTick(
    _baseAmount: BigNumberish,
    _tickDifference: BigNumberish,
    _timeInterval: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRewardAmount(
    _gasUsed: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRewardAmountFor(
    _keeper: string,
    _gasUsed: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRewardBoostFor(
    _bonds: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isKP3RToken0(_pool: string, overrides?: CallOverrides): Promise<boolean>;

  keep3rV2(overrides?: CallOverrides): Promise<string>;

  observe(
    _pool: string,
    _secondsAgo: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      _tickCumulative1: BigNumber;
      _tickCumulative2: BigNumber;
      _success: boolean;
    }
  >;

  quote(_eth: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    BOOST_BASE(overrides?: CallOverrides): Promise<BigNumber>;

    KP3R(overrides?: CallOverrides): Promise<string>;

    KP3R_WETH_POOL(overrides?: CallOverrides): Promise<string>;

    MAX(overrides?: CallOverrides): Promise<BigNumber>;

    MIN(overrides?: CallOverrides): Promise<BigNumber>;

    TARGETBOND(overrides?: CallOverrides): Promise<BigNumber>;

    bonds(_keeper: string, overrides?: CallOverrides): Promise<BigNumber>;

    getKP3RsAtTick(
      _liquidityAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPoolTokens(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<[string, string] & { _token0: string; _token1: string }>;

    getQuoteAtTick(
      _baseAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardAmount(
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardAmountFor(
      _keeper: string,
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardBoostFor(
      _bonds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isKP3RToken0(_pool: string, overrides?: CallOverrides): Promise<boolean>;

    keep3rV2(overrides?: CallOverrides): Promise<string>;

    observe(
      _pool: string,
      _secondsAgo: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        _tickCumulative1: BigNumber;
        _tickCumulative2: BigNumber;
        _success: boolean;
      }
    >;

    quote(_eth: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    BOOST_BASE(overrides?: CallOverrides): Promise<BigNumber>;

    KP3R(overrides?: CallOverrides): Promise<BigNumber>;

    KP3R_WETH_POOL(overrides?: CallOverrides): Promise<BigNumber>;

    MAX(overrides?: CallOverrides): Promise<BigNumber>;

    MIN(overrides?: CallOverrides): Promise<BigNumber>;

    TARGETBOND(overrides?: CallOverrides): Promise<BigNumber>;

    bonds(_keeper: string, overrides?: CallOverrides): Promise<BigNumber>;

    getKP3RsAtTick(
      _liquidityAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPoolTokens(_pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    getQuoteAtTick(
      _baseAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardAmount(
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardAmountFor(
      _keeper: string,
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRewardBoostFor(
      _bonds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isKP3RToken0(_pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    keep3rV2(overrides?: CallOverrides): Promise<BigNumber>;

    observe(
      _pool: string,
      _secondsAgo: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    quote(_eth: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BOOST_BASE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    KP3R(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    KP3R_WETH_POOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TARGETBOND(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bonds(
      _keeper: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getKP3RsAtTick(
      _liquidityAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPoolTokens(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getQuoteAtTick(
      _baseAmount: BigNumberish,
      _tickDifference: BigNumberish,
      _timeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardAmount(
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardAmountFor(
      _keeper: string,
      _gasUsed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRewardBoostFor(
      _bonds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isKP3RToken0(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    keep3rV2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    observe(
      _pool: string,
      _secondsAgo: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    quote(
      _eth: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
